name: Shell
on:
  push:
    branches:
    - main
  pull_request:

jobs:
  run-script:
    runs-on: ubuntu-latest

  steps:
    - name: Repository klonen
      run: git clone https://github.com/tunlu123/Shellscript_ausf-hren.git
    - name: Ausführen
      run: |
      chmod +x script.sh
      ./script.sh